// /constants/adminMockData.js
// Temporary mock data — swap for real API calls (Axios + TanStack Query)
// once the /admin/users and /admin/projects endpoints are wired up.

export const ROLES = ["Admin", "Project Manager", "Team Member"];

export const MOCK_USERS = [
  {
    id: "u001",
    name: "Anisha Rai",
    email: "anisha.rai@clarity.io",
    role: "Admin",
    status: "active",
    projects: 6,
    joined: "2025-02-14",
    lastActive: "2026-07-08T09:12:00",
  },
  {
    id: "u002",
    name: "Bikash Thapa",
    email: "bikash.thapa@clarity.io",
    role: "Project Manager",
    status: "active",
    projects: 4,
    joined: "2025-03-02",
    lastActive: "2026-07-08T07:45:00",
  },
  {
    id: "u003",
    name: "Sarita Gurung",
    email: "sarita.gurung@clarity.io",
    role: "Team Member",
    status: "active",
    projects: 3,
    joined: "2025-04-19",
    lastActive: "2026-07-07T18:20:00",
  },
  {
    id: "u004",
    name: "Prakash Shrestha",
    email: "prakash.shrestha@clarity.io",
    role: "Team Member",
    status: "inactive",
    projects: 1,
    joined: "2025-05-11",
    lastActive: "2026-06-20T11:02:00",
  },
  {
    id: "u005",
    name: "Nisha Khadka",
    email: "nisha.khadka@clarity.io",
    role: "Project Manager",
    status: "active",
    projects: 5,
    joined: "2025-01-30",
    lastActive: "2026-07-08T08:55:00",
  },
  {
    id: "u006",
    name: "Rajan Basnet",
    email: "rajan.basnet@clarity.io",
    role: "Team Member",
    status: "pending",
    projects: 0,
    joined: "2026-06-29",
    lastActive: null,
  },
  {
    id: "u007",
    name: "Muna Adhikari",
    email: "muna.adhikari@clarity.io",
    role: "Team Member",
    status: "active",
    projects: 2,
    joined: "2025-08-08",
    lastActive: "2026-07-06T14:10:00",
  },
  {
    id: "u008",
    name: "Suresh Karki",
    email: "suresh.karki@clarity.io",
    role: "Admin",
    status: "active",
    projects: 7,
    joined: "2024-11-21",
    lastActive: "2026-07-08T09:40:00",
  },
];

export const MOCK_PROJECTS = [
  {
    id: "p001",
    name: "Khana Sanskriti Archive",
    description: "Digital archive documenting traditional Nepali dishes and food history.",
    status: "active",
    priority: "high",
    progress: 68,
    manager: "Nisha Khadka",
    team: ["Anisha Rai", "Sarita Gurung", "Muna Adhikari"],
    tasksTotal: 42,
    tasksDone: 29,
    dueDate: "2026-08-14",
  },
  {
    id: "p002",
    name: "Clarity Admin Panel",
    description: "Role-based dashboard for Admins, Project Managers, and Team Members.",
    status: "active",
    priority: "high",
    progress: 45,
    manager: "Bikash Thapa",
    team: ["Suresh Karki", "Rajan Basnet"],
    tasksTotal: 60,
    tasksDone: 27,
    dueDate: "2026-09-02",
  },
  {
    id: "p003",
    name: "Foodrs Vendor Onboarding",
    description: "Cloudinary-backed vendor flow for public and authenticated users.",
    status: "at-risk",
    priority: "medium",
    progress: 22,
    manager: "Nisha Khadka",
    team: ["Prakash Shrestha", "Muna Adhikari"],
    tasksTotal: 30,
    tasksDone: 7,
    dueDate: "2026-07-25",
  },
  {
    id: "p004",
    name: "Student CRUD Migration",
    description: "Porting the legacy Java Servlet CRUD system to the new stack.",
    status: "on-hold",
    priority: "low",
    progress: 10,
    manager: "Suresh Karki",
    team: ["Rajan Basnet"],
    tasksTotal: 18,
    tasksDone: 2,
    dueDate: "2026-10-30",
  },
  {
    id: "p005",
    name: "Mobile Companion App",
    description: "React Native companion for team members to track daily tasks.",
    status: "completed",
    priority: "medium",
    progress: 100,
    manager: "Bikash Thapa",
    team: ["Sarita Gurung", "Anisha Rai", "Suresh Karki"],
    tasksTotal: 50,
    tasksDone: 50,
    dueDate: "2026-06-10",
  },
  {
    id: "p006",
    name: "Design System v2",
    description: "Extending the glassmorphic component library across every admin view.",
    status: "active",
    priority: "medium",
    progress: 81,
    manager: "Anisha Rai",
    team: ["Muna Adhikari", "Sarita Gurung"],
    tasksTotal: 24,
    tasksDone: 19,
    dueDate: "2026-07-30",
  },
];
